{{- if not .Values.postgresOnly -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "twvault.fullname" . }}-app
  labels:
    app.kubernetes.io/name: {{ include "twvault.name" . }}-app
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "twvault.name" . }}-app
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "twvault.name" . }}-app
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-app.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.app.fullname }}"
        imagePullPolicy: {{ .Values.image.app.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "twvault.fullname" . }}-app
        env:
        - name: ConnectionStrings__Vault__Server
          value: {{ include "twvault.dbHostname" . | quote }}
        ports:
          - name: http
            containerPort: 5000
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /script/vault.js
            port: http
        readinessProbe:
          httpGet:
            path: /script/vault.js
            port: http
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - mountPath: /opt/twvault/script
          name: scripts
        - mountPath: /opt/twvault/logs
          name: logs
      initContainers:
        {{- include "twvault.waitForDb.available" . | nindent 6 }}
      - name: run-migrations
        image: {{ .Values.image.migrate.fullname }}
        imagePullPolicy: {{ .Values.image.app.pullPolicy }}
        args:
        - {{ include "twvault.connectionString" . | quote }}
      volumes:
      - name: scripts
        secret:
          secretName: {{ include "twvault.scripts.secretName" . }}
      - name: logs
        persistentVolumeClaim:
          claimName: {{ include "twvault.fullname" . }}-app
{{- end -}}