{{- if not .Values.postgresOnly -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "twvault.scripts.secretName" . }}
  labels:
    app.kubernetes.io/name: {{ include "twvault.name" . }}-app
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  vault.js: {{ .Files.Get .Values.script.vault | b64enc }}
  main.js: {{ .Files.Get .Values.script.main | b64enc }}
{{- end -}}